/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni/jni.h"
/* Header for class com_romotive_library_RomoNativeInterface */

#ifndef _Included_com_romotive_library_RomoCommandInterface
#define _Included_com_romotive_library_RomoCommandInterface
extern "C" 
{
/*
 * Class:     com_romotive_library_RomoNativeInterface
 * Method:    nativeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_romotive_library_RomoCommandInterface_nativeShutdown
    (JNIEnv *, jobject);
 
/*
 * Class:     com_romotive_library_RomoNativeInterface
 * Method:    playMotorCommand
 * Signature: (I,I)V
 */
JNIEXPORT void JNICALL Java_com_romotive_library_RomoCommandInterface_playMotorCommand
    (JNIEnv *, jobject, jint, jint);
    
/*
 * Class:     com_romotive_library_RomoNativeInterface
 * Method:    playAuxCommand
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_romotive_library_RomoCommandInterface_playAuxCommand
    (JNIEnv *, jobject, jint);
}
#endif
